# Docker Compose file for testing
version: "2"
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ..:/code
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:3.2.1
