# Docker Compose file for testing
version: "2"
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    volumes:
      - ..:/code
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:3.2.1
