services:

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: metabrainz-dev
    volumes:
      - ..:/code/metabrainz
    depends_on:
      - meb_db
      - redis

  meb_db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:3.2.1
