# Docker Compose file for development
version: "2"

volumes:
  db:

services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    command: python /code/manage.py runserver -h 0.0.0.0 -p 80
    volumes:
      - ../data/replication_packets:/data/replication_packets
      - ../data/json_dumps:/data/json_dumps
      - ../data/logos:/code/metabrainz/static/img/user_logos
      - ..:/code
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
      - mail

  db:
    image: postgres:12.3
    volumes:
      - db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"

  redis:
    image: redis:3.2.1

  mail:
    build:
      context: ./smtp/
      dockerfile: Dockerfile
    environment:
      MAILDOMAIN: metabrainz.org
    ports:
      - "25:25"
